### ISSUE TITLE
Open File Under Cursor

### ISSUE THREAD

**Issue by lundeen-bryan** [robole/vscode-file-bunny#13]
Very simple feature request is to have File Bunny open the file under cursor. Please include the open to left or right options if possible, otherwise, I'd still be extremely grateful to be able to open the file under the cursor. 

Thank you!

**Comment by robole** [comment]
Hi @lundeen-bryan ,

What do you mean by "the file under cursor"? WhereI is this happening? Can you provide a screenshot or more specific description please?

Best wishes

**Comment by lundeen-bryan** [comment]
Hi @robole ,

Given that the user has a file open, such as an HTML document. 
And the file has text of a filename such as "style.css"
And the user uses the mouse to place the cursor within the filename "style.css" text in the file that is open.
Then file bunny would have a command to open the file that is "under" the cursor, e.g., the style.css file. 

Does that make more sense?

**Comment by robole** [comment]
Yes, makes sense.

There is already a command for this called `Open Link`. Alternatively, you hold the `Alt` key and click the link to the file. Give it a try! If you are satisfied that the command covers your use case, you can close the issue.

Thanks

**Comment by robole** [comment]
The full command name is `Open link`. It is a builtin VS Code command,.

**Comment by robole** [comment]
I will pass on this idea for now. This functionality is mostly covered by the builtin commands `Open Link` and `Go to Definition`. If you want a more comprehensive approach, you can use the [Open File extension](https://marketplace.visualstudio.com/items?itemName=Fr43nk.seito-openfile) that you mentioned.
