### ISSUE TITLE
Unable to rename active file

### ISSUE THREAD

**Issue by neta540** [robole/vscode-file-bunny#14]
Choosing File Bunny: Rename Active File from the command palette results with an error. 

**Screenshot**
![image](https://github.com/robole/vscode-file-bunny/assets/19378426/4d91f745-ab40-4133-afd6-c4c03a65513d)

**Platform info (please complete the following information):**
Windows 11 23H2
Visual Studio Code 1.85.0
Electron: 25.9.7
NodeJS: 18.15.0

**Comment by robole** [comment]
Fixed in v1.8.1
