### ISSUE TITLE
Deleted Files can not be found in Trash (Recycle Bin).

### ISSUE THREAD

**Issue by PamlJam** [robole/vscode-file-bunny#16]
**Describe the bug**

After I clicked the command `Delete File` or `Delete Active File` in VS Code Command Palette,

The deleted files can not be found in Trash (Recycle Bin).

**Additional context**

- OS = Windows 10 

- VS Code Version = 1.85.1

**Comment by robole** [comment]
Were you working in a remote workspace?

Were you using WSL?

There is an existing issue related to this: #10. 

The code around this functionality has not changed in a long time, this is likely to be an issue with VS Code.

**Comment by PamlJam** [comment]
Thanks for your reply.

I was using VS Code locally, and I wasn't using WSL.

**Comment by robole** [comment]
I checked in the VS Code Insiders v1.86, it appears a fix will be coming in the next release. When you update to v1.86, you can check if the issue is resolved and close the issue.

thanks.

**Comment by PamlJam** [comment]
Since there are currently no updates in `VS Code`, I downloaded the latest(v1.86) `VS Code Insider` and tried on it.

It finally works. The deleted files move to Trash (Recycle Bin).

Hope the issue will be solved when the `VS Code` is able to update to v1.86.

**Comment by robole** [comment]
This issue is resolved in v1.86.

If you are happy with the extension, can you star the repo please?

Best wishes

Rob

**Comment by PamlJam** [comment]
Until just now I noticed it. Appreciate for your brilliant work.
