### ISSUE TITLE
Can't install file bunny on VS Code 1.82

### ISSUE THREAD

**Issue by halloleo** [robole/vscode-file-bunny#17]
**Describe the bug**

Can't install file bunny on VS Code 1.82. i get the error "Error: Unable to install extension 'robole.file-bunny' as it is not compatible with VS Code '1.82.0'."

**To Reproduce**

Install `robole.file-bunny-2.2.0.vsix` fil into VS Code 1.82.

**Expected behavior**

File Bunny should install without problems. I don't think File Bunny  uses very new features of VS Code.

**Platform info (please complete the following information):**

RHEL 7 Linux

**Additional context**

I cannot upgrade VS Code on that machine, because of glibc issues.

**Comment by robole** [comment]
hi @halloleo ,

Thanks for your interest in the extension.

In version 2.0 of the extension, I upgraded the minimum version of VS Code that the extension supports to use more features of the API. You can read in the [changelog](https://github.com/robole/vscode-file-bunny/blob/main/CHANGELOG.md) why I did this  exactly. The short of it is that  I wanted to use the recently added `Tab` and  `TabGroup`  interfaces to be able to delete any file type open in editor.

You can download and use version 1.10.2 that supports earlier versions of VS Code.

If you want to use the latest version of the extension on your machine, you will need to do the legwork. I don't have time to support niche requests. I'm not sure when the `Tab` and  `TabGroup` interfaces were added to the API, you could look through the release notes to check and you could change the `engines` field in the package.json to an earlier version and test the extension to ensure that the affected commands work. I will review a PR if you do this. 

Just keep in mind that there are some improvements in the VS Code API that I am watching to improve the extension, so raising the minimum supported version will happen again some time in the future. The better solution always it is that the solution comes from the platform, not related software.

Kind Regards,

Rob

**Comment by halloleo** [comment]
Thanks for the detailed reply! Totally understand it.

I will try to see whether the change in `pacakge.json` makes it work under VSC 1.82.
