### ISSUE TITLE
Add a custom shortcut to open all Bunny commands directly

### ISSUE THREAD

**Issue by jonnyso** [robole/vscode-file-bunny#6]
Hey there,

Normally if you want to search for a specific command first you need to type ctrl+p then type >bunny. It would be nice to be able to skip that and go directly to the search options.

I've been using the shortcut bellow to achieve that

`{
        "key": "shift+Space",
        "command": "workbench.action.quickOpen",
        "args": ">bunny "
    }`
    
 Of course, people could just add it on their own but it would be nice to have by default to make things a little smoother.

**Comment by robole** [comment]
Hi @jonnyso ,

Thanks for the suggestion. Its a good idea.

I added it to [my blog post on keyboard shortcuts](https://www.roboleary.net/2022/02/28/vscode-keyboard-fu-custom-keyboard-shortcuts.html#keybindings-for-file-management) that is linked to in the README for the extension. 

I think it is better to let people pick their own keybindings for commands for the majority of cases, it is a personal choice and it is difficult to avoid overriding a user's other keybindings (you don't know what they are). Recently someone raised [an issue](https://github.com/robole/vscode-file-bunny/issues/5) on the keybinding I included in this extension for the `home` key saying that they were confused by it. So I will close this.

Thanks
